# Generated by Django 2.2.24 on 2021-06-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pdf_url', models.URLField(max_length=500)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('numero_orden', models.CharField(blank=True, max_length=50)),
                ('fecha_factura', models.DateField(blank=True)),
                ('fecha_vencimiento', models.DateField(blank=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
                ('numero_banco', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('monto', models.FloatField(blank=True)),
                ('ivu', models.FloatField(blank=True)),
                ('monto_total', models.FloatField(blank=True)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion_empresa', models.CharField(max_length=200)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=200)),
            ],
        ),
    ]
