# Generated by Django 2.2.24 on 2021-06-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ivu',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_total',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
